import { DatePipe } from '@angular/common';
import { ChangeDetectionStrategy, Component, inject, signal } from '@angular/core';
import { LucideRotateCcw, LucideTrash2 } from '@lucide/angular';
import { TrashEntry } from '../../core/trash/trash.models';
import { TrashService } from '../../core/trash/trash.service';
import { AppDialogComponent } from '../../shared/app-dialog/app-dialog.component';

@Component({selector:'app-trash-page',imports:[DatePipe,LucideRotateCcw,LucideTrash2,AppDialogComponent],changeDetection:ChangeDetectionStrategy.OnPush,template:`<main class="trash-page" dir="rtl"><header><div><small>النظام</small><h1>سلة المهملات</h1><p>يمكن استعادة العناصر خلال 30 يومًا قبل حذفها نهائيًا.</p></div></header><section>@if(!trash.entries().length){<div class="empty"><svg lucideTrash2></svg><h2>سلة المهملات فارغة</h2><p>ستظهر هنا العناصر المحذوفة مؤقتًا.</p></div>}@else{<div class="table-wrap"><table><thead><tr><th>العنصر</th><th>النوع</th><th>تاريخ الحذف</th><th>الحذف النهائي</th><th>الإجراءات</th></tr></thead><tbody>@for(item of trash.entries();track item.trashId){<tr><td><strong>{{item.entityLabel}}</strong>@if(item.financialRecord){<small>سجل مالي</small>}</td><td>{{typeLabel(item)}}</td><td>{{item.deletedAt|date:'yyyy/MM/dd، HH:mm':'Africa/Cairo'}}</td><td>{{item.expiresAt|date:'yyyy/MM/dd':'Africa/Cairo'}}</td><td><button class="restore" type="button" (click)="trash.restore(item.trashId)"><svg lucideRotateCcw></svg>استعادة</button><button class="delete" type="button" (click)="selected.set(item)"><svg lucideTrash2></svg>حذف نهائي</button></td></tr>}</tbody></table></div>}</section>@if(selected();as item){<app-dialog title="حذف نهائي؟" [subtitle]="item.entityLabel" (closed)="selected.set(null)"><p>لن يمكن استعادة هذا العنصر بعد تأكيد الحذف النهائي.</p><div dialog-actions><button class="restore" (click)="selected.set(null)">إلغاء</button><button class="delete" (click)="permanent(item)">تأكيد الحذف النهائي</button></div></app-dialog>}</main>`,styles:[`.trash-page{padding:1.5rem;color:var(--text)}header{margin-bottom:1.25rem}h1{margin:.2rem 0;color:var(--forest);font-size:1.75rem}header p,header small{color:var(--muted)}section{overflow:hidden;border:1px solid var(--border);border-radius:var(--radius);background:#fff}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{padding:1rem;text-align:right;border-bottom:1px solid var(--border)}th{background:#f7f9f7}td small{display:block;color:#b96f5d}.empty{text-align:center;padding:4rem;color:var(--muted)}.empty svg{width:2rem}.restore,.delete{display:inline-flex;align-items:center;gap:.35rem;margin-inline-end:.4rem;padding:.55rem .75rem;border-radius:.5rem;background:#fff;font:inherit;cursor:pointer}.restore{border:1px solid var(--primary);color:var(--primary)}.delete{border:1px solid #c83d3d;color:#c83d3d}.restore svg,.delete svg{width:1rem}@media(max-width:700px){.trash-page{padding:1rem}th,td{white-space:nowrap}}`]} )
export class TrashPage{readonly trash=inject(TrashService);readonly selected=signal<TrashEntry|null>(null);permanent(item:TrashEntry):void{this.trash.permanentlyDelete(item.trashId);this.selected.set(null)}typeLabel(item:TrashEntry):string{return({category:'تصنيف',brand:'علامة تجارية',article:'مقال',discount:'كوبون',staff:'مستخدم',invoice:'فاتورة',payment:'دفعة',shipment:'شحنة',return:'طلب مرتجع'}as const)[item.entityType]}}
