import { SettingsSection, SettingsValues } from '../models/settings.model';

export const SETTINGS_SECTIONS: readonly SettingsSection[] = [
  { id: 'store', label: 'إعدادات المتجر', eyebrow: 'الإعدادات / المتجر', title: 'إعدادات المتجر', subtitle: 'حدّث هوية المتجر وبيانات التواصل التي تظهر للعملاء.', cards: [
    { title: 'بيانات المتجر', description: 'المعلومات الأساسية المستخدمة في الفواتير وصفحات التواصل.', fields: [
      { key: 'storeName', label: 'اسم المتجر', type: 'text', required: true }, { key: 'email', label: 'البريد الإلكتروني', type: 'email', required: true }, { key: 'phone', label: 'رقم خدمة العملاء', type: 'tel', required: true }, { key: 'commercialName', label: 'الاسم التجاري', type: 'text' }, { key: 'address', label: 'العنوان', type: 'textarea', required: true },
    ] }, { title: 'حالة المتجر', description: 'تحكّم في استقبال الطلبات ورسالة الإغلاق المؤقت.', fields: [
      { key: 'acceptOrders', label: 'استقبال الطلبات الجديدة', type: 'toggle', hint: 'يمكن إيقافه مؤقتًا أثناء الصيانة.' }, { key: 'maintenanceMessage', label: 'رسالة الإغلاق المؤقت', type: 'textarea' },
    ] },
  ] },
  { id: 'orders', label: 'إعدادات الطلبات', eyebrow: 'الإعدادات / الطلبات', title: 'إعدادات الطلبات', subtitle: 'اضبط ترقيم الطلبات وسياسات التأكيد والإلغاء.', cards: [
    { title: 'ترقيم الطلبات', description: 'صيغة الرقم الظاهر للعميل وفريق التشغيل.', fields: [{ key: 'orderPrefix', label: 'بادئة رقم الطلب', type: 'text', required: true }, { key: 'nextOrderNumber', label: 'الرقم التالي', type: 'number', required: true, min: 1 }] },
    { title: 'سير الطلب', description: 'خيارات التشغيل الافتراضية للطلبات الجديدة.', fields: [{ key: 'autoConfirmPaid', label: 'تأكيد الطلبات المدفوعة تلقائيًا', type: 'toggle' }, { key: 'allowCustomerCancellation', label: 'السماح للعميل بالإلغاء', type: 'toggle' }, { key: 'cancellationMinutes', label: 'مهلة الإلغاء بالدقائق', type: 'number', min: 0, max: 1440 }] },
  ] },
  { id: 'inventory', label: 'إعدادات المخزون', eyebrow: 'الإعدادات / المخزون', title: 'إعدادات المخزون', subtitle: 'حدّد مستويات التنبيه وسلوك حجز الكميات.', cards: [
    { title: 'تنبيهات الكمية', description: 'قيم افتراضية عند غياب قيمة خاصة بالمنتج.', fields: [{ key: 'lowStockThreshold', label: 'حد المخزون المنخفض', type: 'number', required: true, min: 0 }, { key: 'outOfStockThreshold', label: 'حد نفاد المخزون', type: 'number', required: true, min: 0 }, { key: 'notifyDaily', label: 'إرسال ملخص يومي للتنبيهات', type: 'toggle' }] },
    { title: 'سياسة الحجز', description: 'تنظيم الكمية المتاحة أثناء تجهيز الطلب.', fields: [{ key: 'reserveOnOrder', label: 'حجز المخزون عند إنشاء الطلب', type: 'toggle' }, { key: 'allowBackorder', label: 'السماح بالطلب عند نفاد الكمية', type: 'toggle' }] },
  ] },
  { id: 'payments', label: 'وسائل الدفع', eyebrow: 'الإعدادات / الدفع', title: 'وسائل الدفع', subtitle: 'فعّل وسائل التحصيل المتاحة للعملاء وأضف وسيلة داخلية.', cards: [{ title: 'خيارات التحصيل', description: 'لن تظهر الوسيلة للعميل إذا كانت غير مفعّلة.', fields: [{ key: 'cashOnDelivery', label: 'الدفع عند الاستلام', type: 'toggle' }, { key: 'bankCard', label: 'البطاقات البنكية', type: 'toggle' }, { key: 'wallet', label: 'المحافظ الإلكترونية', type: 'toggle' }, { key: 'cashLimit', label: 'الحد الأقصى للدفع عند الاستلام', type: 'number', min: 0 }] }] },
  { id: 'shipping', label: 'طرق الشحن', eyebrow: 'الإعدادات / الشحن', title: 'طرق الشحن', subtitle: 'اضبط طرق التوصيل وتكلفتها والمدة المتوقعة.', cards: [{ title: 'التوصيل المحلي', description: 'الإعدادات الافتراضية للشحن من فروع نبته.', fields: [{ key: 'branchDelivery', label: 'التوصيل من الفرع', type: 'toggle' }, { key: 'pickup', label: 'الاستلام من الفرع', type: 'toggle' }, { key: 'defaultFee', label: 'رسوم الشحن الافتراضية', type: 'number', min: 0 }, { key: 'deliveryDays', label: 'مدة التوصيل بالأيام', type: 'number', min: 1, max: 30 }] }] },
  { id: 'taxes', label: 'الضرائب', eyebrow: 'الإعدادات / الضرائب', title: 'إعدادات الضرائب', subtitle: 'حدّد طريقة عرض الضريبة والبيانات القانونية على الفاتورة.', cards: [{ title: 'ضريبة القيمة المضافة', description: 'تطبق النسبة على البنود الخاضعة وفق إعدادات المنتج.', fields: [{ key: 'taxEnabled', label: 'تفعيل احتساب الضريبة', type: 'toggle' }, { key: 'taxRate', label: 'نسبة الضريبة %', type: 'number', min: 0, max: 100 }, { key: 'pricesIncludeTax', label: 'الأسعار المعروضة تشمل الضريبة', type: 'toggle' }, { key: 'taxNumber', label: 'رقم التسجيل الضريبي', type: 'text' }] }] },
  { id: 'notifications', label: 'الإشعارات', eyebrow: 'الإعدادات / الإشعارات', title: 'إعدادات الإشعارات', subtitle: 'اختر التنبيهات التشغيلية المهمة وقنوات وصولها.', cards: [
    { title: 'الأحداث', description: 'فعّل الإشعارات التي يحتاجها فريق التشغيل.', fields: [{ key: 'newOrders', label: 'الطلبات الجديدة', type: 'toggle' }, { key: 'lowStock', label: 'المخزون المنخفض', type: 'toggle' }, { key: 'failedPayments', label: 'عمليات الدفع الفاشلة', type: 'toggle' }, { key: 'delayedShipping', label: 'الشحنات المتأخرة', type: 'toggle' }] },
    { title: 'القنوات', description: 'قنوات إرسال إشعارات الإدارة.', fields: [{ key: 'emailNotifications', label: 'البريد الإلكتروني', type: 'toggle' }, { key: 'dashboardNotifications', label: 'داخل لوحة الإدارة', type: 'toggle' }, { key: 'notificationEmail', label: 'بريد استقبال التنبيهات', type: 'email' }] },
  ] },
  { id: 'locale', label: 'اللغة والعملة', eyebrow: 'الإعدادات / اللغة والعملة', title: 'اللغة والعملة', subtitle: 'اضبط التنسيق المحلي الافتراضي للوحة والمتجر.', cards: [{ title: 'التنسيق المحلي', description: 'يؤثر على عرض التواريخ والأرقام والأسعار.', fields: [
    { key: 'language', label: 'اللغة الافتراضية', type: 'select', options: [{ label: 'العربية', value: 'ar' }, { label: 'English', value: 'en' }] }, { key: 'currency', label: 'العملة', type: 'select', options: [{ label: 'الجنيه المصري (ج.م)', value: 'EGP' }, { label: 'الريال السعودي (ر.س)', value: 'SAR' }, { label: 'الدولار الأمريكي ($)', value: 'USD' }] }, { key: 'timezone', label: 'المنطقة الزمنية', type: 'select', options: [{ label: 'القاهرة (UTC+2)', value: 'Africa/Cairo' }, { label: 'الرياض (UTC+3)', value: 'Asia/Riyadh' }] }, { key: 'firstDayOfWeek', label: 'أول أيام الأسبوع', type: 'select', options: [{ label: 'السبت', value: 'saturday' }, { label: 'الأحد', value: 'sunday' }] },
  ] }] },
] as const;

export const DEFAULT_SETTINGS: Readonly<Record<string, SettingsValues>> = {
  store: { storeName: 'نبته للحلول الزراعية', email: 'hello@nabtah.example', phone: '01000000000', commercialName: 'نبته', address: 'القاهرة، جمهورية مصر العربية', acceptOrders: true, maintenanceMessage: 'نعود لاستقبال طلباتكم قريبًا.' },
  orders: { orderPrefix: 'ORD', nextOrderNumber: 1050, autoConfirmPaid: true, allowCustomerCancellation: true, cancellationMinutes: 30 },
  inventory: { lowStockThreshold: 10, outOfStockThreshold: 0, notifyDaily: true, reserveOnOrder: true, allowBackorder: false }, payments: { cashOnDelivery: true, bankCard: true, wallet: false, cashLimit: 10000 }, shipping: { branchDelivery: true, pickup: true, defaultFee: 65, deliveryDays: 3 }, taxes: { taxEnabled: true, taxRate: 14, pricesIncludeTax: true, taxNumber: '200-000-000' }, notifications: { newOrders: true, lowStock: true, failedPayments: true, delayedShipping: true, emailNotifications: true, dashboardNotifications: true, notificationEmail: 'operations@nabtah.example' }, locale: { language: 'ar', currency: 'EGP', timezone: 'Africa/Cairo', firstDayOfWeek: 'saturday' },
};
