import { Component, computed, inject, input, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { LucideArrowRight, LucideCheck, LucideMapPin, LucidePhone, LucidePrinter, LucideShoppingBag, LucideUserRound } from '@lucide/angular';
import { DashboardStore } from '../dashboard.store';
import { OrderStatus } from '../models';
import { StatusBadge } from '../shared/status-badge';

@Component({
  imports: [RouterLink, LucideArrowRight, LucideCheck, LucideMapPin, LucidePhone, LucidePrinter, LucideShoppingBag, LucideUserRound, StatusBadge],
  template: `
    @if(order(); as item){<div class="back-row"><a routerLink="/orders"><svg lucideArrowRight></svg>العودة للطلبات</a><button class="btn secondary" type="button" (click)="store.showToast('تم إرسال أمر الطباعة')"><svg lucidePrinter></svg>طباعة</button></div><header class="order-head"><div><span>طلب {{ item.orderNumber }}</span><h1>{{ item.customer }}</h1><p>{{ item.createdAt }}</p></div><app-status-badge [value]="item.status"/></header>
      <div class="details-grid"><section class="panel"><h2>تحديث حالة الطلب</h2><div class="steps">@for(step of steps; track step.value; let i=$index){<button type="button" [class.done]="statusIndex(item.status)>=i" [class.current]="item.status===step.value" (click)="selectStatus.set(step.value)"><span>@if(statusIndex(item.status)>i){<svg lucideCheck></svg>}@else { {{ i+1 }} }</span>{{ step.label }}</button>}</div><label>الحالة الجديدة<select #next [value]="selectStatus()" (change)="setSelected(next.value)">@for(step of steps;track step.value){<option [value]="step.value">{{ step.label }}</option>}<option value="cancelled">إلغاء الطلب</option></select></label><label>ملاحظة داخلية<textarea #note placeholder="أضف ملاحظة لفريق التجهيز (اختياري)"></textarea></label><button class="btn" type="button" (click)="update(item.id); note.value=''">حفظ التحديث</button></section>
      <aside><section class="panel info"><h2>بيانات العميل</h2><p><svg lucideUserRound></svg><span><small>الاسم</small>{{ item.customer }}</span></p><p><svg lucidePhone></svg><span><small>رقم الهاتف</small>{{ item.mobile }}</span></p><p><svg lucideMapPin></svg><span><small>عنوان الشحن</small>{{ item.governorate }}، مركز المدينة، شارع المحطة</span></p></section><section class="panel totals"><h2>ملخص الدفع</h2><p><span>المنتجات ({{ item.itemsCount }})</span><strong>{{ (item.total-85).toLocaleString('ar-EG') }} ج.م</strong></p><p><span>الشحن</span><strong>85 ج.م</strong></p><p class="total"><span>الإجمالي</span><strong>{{ item.total.toLocaleString('ar-EG') }} ج.م</strong></p><small>{{ item.payment }}</small></section></aside></div>
    }@else{<section class="panel missing"><svg lucideShoppingBag></svg><h1>الطلب غير موجود</h1><a class="btn" routerLink="/orders">العودة إلى الطلبات</a></section>}
  `,
  styles: [`
    .back-row{display:flex;justify-content:space-between;align-items:center;margin-bottom:1rem}.back-row>a{display:flex;align-items:center;gap:.4rem;color:var(--brand);font-size:.85rem}.back-row lucide-icon{width:1rem}.order-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.5rem}.order-head span{color:var(--muted);font-size:.8rem}.order-head h1{margin:.2rem 0;color:var(--forest);font:700 1.6rem var(--font-display)}.order-head p{margin:0;color:var(--muted);font-size:.78rem}.details-grid{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(17rem,.7fr);gap:1rem}.panel{padding:1.25rem;background:#fff;border:1px solid var(--border);border-radius:var(--radius);box-shadow:var(--shadow)}.panel h2{margin:0 0 1rem;font:700 1rem var(--font-display);color:var(--forest)}.steps{display:flex;margin:1.7rem 0 2rem}.steps button{position:relative;display:grid;justify-items:center;gap:.45rem;flex:1;border:0;background:none;color:var(--muted);font:500 .72rem var(--font-body);cursor:pointer}.steps button:not(:last-child)::after{content:'';position:absolute;top:1rem;right:calc(50% + 1rem);width:calc(100% - 2rem);height:2px;background:var(--border)}.steps button span{position:relative;z-index:1;display:grid;place-items:center;width:2rem;height:2rem;border:2px solid var(--border);border-radius:50%;background:#fff}.steps button.done span{border-color:var(--brand);background:var(--brand);color:#fff}.steps button.current{color:var(--brand);font-weight:700}.steps lucide-icon{width:.9rem}.panel>label{display:grid;gap:.35rem;margin-top:1rem;color:var(--text);font-size:.82rem}.panel>.btn{margin-top:1rem}aside{display:grid;align-content:start;gap:1rem}.info p{display:flex;align-items:flex-start;gap:.7rem;margin:1rem 0}.info lucide-icon{width:1.1rem;color:var(--brand)}.info span{display:grid;font-size:.82rem}.info small{color:var(--muted);font-size:.68rem}.totals p{display:flex;justify-content:space-between;color:var(--muted);font-size:.8rem}.totals strong{color:var(--text)}.totals .total{padding-top:.9rem;border-top:1px solid var(--border);font-size:.95rem}.totals .total strong{color:var(--forest);font-size:1.05rem}.totals>small{display:block;padding:.65rem;border-radius:.55rem;background:var(--pale);color:var(--brand);text-align:center}.missing{display:grid;justify-items:center;gap:.7rem;padding:4rem;text-align:center}.missing lucide-icon{width:3rem;color:var(--muted)}@media(max-width:850px){.details-grid{grid-template-columns:1fr}}@media(max-width:600px){.steps{overflow:auto}.steps button{min-width:5.5rem}.back-row .btn{padding-inline:.65rem}}
  `],
})
export class OrderDetailsPage {
  readonly id = input.required<string>(); readonly store = inject(DashboardStore); readonly order = computed(() => this.store.orders().find((item) => item.id === this.id())); readonly selectStatus = signal<OrderStatus>('pending');
  readonly steps: { value: OrderStatus; label: string }[] = [{value:'pending',label:'مراجعة'},{value:'confirmed',label:'تأكيد'},{value:'processing',label:'تجهيز'},{value:'shipped',label:'شحن'},{value:'delivered',label:'اكتمال'}];
  statusIndex(status: OrderStatus): number { return this.steps.findIndex((step) => step.value === status); }
  setSelected(value: string): void { this.selectStatus.set(value as OrderStatus); }
  update(id: string): void { this.store.updateOrderStatus(id,this.selectStatus()); }
}



