import { computed, inject, Injectable, signal } from '@angular/core';
import { catchError, delay, finalize, Observable, of, take, tap } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { PaymentFilters, PaymentPage, PaymentRecord, PaymentStatus, PaymentSummary } from '../models/payment.models';
import { DEMO_PAYMENTS } from './payments.demo';
import { PaymentsApiService } from './payments-api.service';
import { TrashService } from '../../../core/trash/trash.service';
export const DEFAULT_PAYMENT_FILTERS: PaymentFilters = { search: '', status: '', method: '', period: 'all', page: 1, perPage: 5 };
@Injectable()
export class PaymentsStore {
  private readonly trash=inject(TrashService);
  private readonly api = inject(PaymentsApiService); private readonly demoRecordsState = signal<readonly PaymentRecord[]>(DEMO_PAYMENTS); private readonly dataState = signal<PaymentPage | null>(null); private readonly filtersState = signal(DEFAULT_PAYMENT_FILTERS); private readonly loadingState = signal(false); private readonly errorState = signal<string | null>(null); private readonly downloadingState = signal(false); private readonly feedbackState = signal<string | null>(null);
  readonly data = this.dataState.asReadonly(); readonly filters = this.filtersState.asReadonly(); readonly loading = this.loadingState.asReadonly(); readonly error = this.errorState.asReadonly(); readonly downloading = this.downloadingState.asReadonly(); readonly feedback = this.feedbackState.asReadonly(); readonly items = computed(() => this.dataState()?.items ?? []); readonly summary = computed<PaymentSummary>(() => this.dataState()?.summary ?? { totalAmount: 0, paidAmount: 0, pendingAmount: 0, refundedAmount: 0, paidCount: 0, pendingCount: 0, refundedCount: 0 }); readonly totalPages = computed(() => Math.max(1, Math.ceil((this.dataState()?.total ?? 0) / this.filtersState().perPage))); readonly hasFilters = computed(() => { const filters = this.filtersState(); return !!(filters.search || filters.status || filters.method || filters.period !== 'all'); });
  constructor(){this.demoRecordsState.update(items=>items.filter(item=>!this.trash.isTrashed('payment',item.id)));}
  setFilters(patch: Partial<PaymentFilters>): void { this.filtersState.update((value) => ({ ...value, ...patch })); } reset(): void { this.filtersState.set(DEFAULT_PAYMENT_FILTERS); }
  load(): Observable<PaymentPage> { this.loadingState.set(true); this.errorState.set(null); const request = environment.demoAdmin ? this.demoList(this.filtersState()) : this.api.list(this.filtersState()); return request.pipe(tap((data) => this.dataState.set(data)), catchError(() => { this.errorState.set('تعذر تحميل سجل المدفوعات.'); return of(this.dataState() ?? { items: [], summary: this.summary(), total: 0, page: 1, perPage: 5 }); }), finalize(() => this.loadingState.set(false))); }
  updateStatus(id: string, status: PaymentStatus): void { if (!environment.demoAdmin) { this.feedbackState.set('هذا الإجراء ينتظر عقد Laravel المعتمد.'); return; } this.demoRecordsState.update((items) => items.map((item) => item.id === id ? { ...item, status } : item)); this.feedbackState.set(status === 'paid' ? 'تم تسجيل العملية كمدفوعة في بيئة العرض.' : 'تم تسجيل الاسترداد الجزئي في بيئة العرض.'); this.demoList(this.filtersState()).pipe(take(1)).subscribe((page) => this.dataState.set(page)); }
  delete(record:PaymentRecord):void{if(!environment.demoAdmin){this.feedbackState.set('حذف المدفوعات ينتظر عقد Laravel والصلاحية المعتمدة.');return;}this.demoRecordsState.update(items=>items.filter(item=>item.id!==record.id));this.feedbackState.set('تم نقل عملية الدفع إلى سلة المهملات لمدة 30 يومًا.');this.demoList(this.filtersState()).pipe(take(1)).subscribe(page=>this.dataState.set(page));}
  clearFeedback(): void { this.feedbackState.set(null); }
  download(): void { if (this.downloadingState()) return; this.downloadingState.set(true); const source = environment.demoAdmin ? of(this.csv()).pipe(delay(200)) : this.api.report(this.filtersState()); source.pipe(take(1), tap((blob) => this.save(blob)), catchError(() => { this.errorState.set('تعذر تنزيل تقرير المدفوعات.'); return of(null); }), finalize(() => this.downloadingState.set(false))).subscribe(); }
  private filtered(filters: PaymentFilters): PaymentRecord[] { const search = filters.search.trim().toLocaleLowerCase('ar'); const limit = filters.period === 'today' ? 86400000 : filters.period === 'week' ? 604800000 : filters.period === 'month' ? 2592000000 : Infinity; return this.demoRecordsState().filter((item) => (!search || [item.paymentNumber, item.orderNumber, item.customerName].some((value) => value.toLocaleLowerCase('ar').includes(search))) && (!filters.status || item.status === filters.status) && (!filters.method || item.method === filters.method) && (Date.now() - Date.parse(item.createdAt) <= limit)); }
  private demoList(filters: PaymentFilters): Observable<PaymentPage> { const rows = this.filtered(filters); const sum = (items: readonly PaymentRecord[]) => items.reduce((total, item) => total + item.amount, 0); const paid = rows.filter((item) => item.status === 'paid'); const pending = rows.filter((item) => item.status === 'pending'); const refunded = rows.filter((item) => item.status === 'partially_refunded'); const summary = { totalAmount: sum(rows), paidAmount: sum(paid), pendingAmount: sum(pending), refundedAmount: sum(refunded), paidCount: paid.length, pendingCount: pending.length, refundedCount: refunded.length }; const start = (filters.page - 1) * filters.perPage; return of({ items: rows.slice(start, start + filters.perPage), summary, total: rows.length, page: filters.page, perPage: filters.perPage }).pipe(delay(120)); }
  private csv(): Blob { const rows = this.filtered(this.filtersState()).map((item) => [item.paymentNumber, item.orderNumber, item.customerName, item.method, item.amount, item.status, item.createdAt.slice(0, 10)]); return new Blob(['\ufeff', [['رقم العملية', 'رقم الطلب', 'العميل', 'وسيلة الدفع', 'المبلغ', 'الحالة', 'التاريخ'], ...rows].map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }); }
  private save(blob: Blob): void { const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `payments-${new Date().toISOString().slice(0, 10)}.csv`; link.click(); URL.revokeObjectURL(url); }
}
