import { Routes } from '@angular/router';
import { adminGuard, authGuard, guestGuard } from './core/guards/auth.guards';
import { unsavedChangesGuard } from './core/guards/unsaved-changes.guard';

export const routes: Routes = [
  {
    path: '',
    loadComponent: () => import('./core/layout/public-layout.component').then((m) => m.PublicLayoutComponent),
    children: [
      { path: '', loadComponent: () => import('./features/home/home.page').then((m) => m.HomePage), data: { title: 'الرئيسية' } },
      { path: 'shop', loadComponent: () => import('./features/catalog/catalog.page').then((m) => m.CatalogPage), data: { title: 'المتجر' } },
      { path: 'search', loadComponent: () => import('./features/search/search.page').then((m) => m.SearchPage), data: { title: 'البحث' } },
      { path: 'products/:slug', loadComponent: () => import('./features/product-details/product-details.page').then((m) => m.ProductDetailsPage) },
      { path: 'companies', loadComponent: () => import('./features/companies/companies.page').then((m) => m.CompaniesPage), data: { title: 'الشركات' } },
      { path: 'companies/:slug', loadComponent: () => import('./features/companies/company-details.page').then((m) => m.CompanyDetailsPage) },
      { path: 'brands', loadComponent: () => import('./features/brands/brands.page').then((m) => m.BrandsPage), data: { title: 'العلامات' } },
      { path: 'brands/:slug', loadComponent: () => import('./features/brands/brand-details.page').then((m) => m.BrandDetailsPage) },
      { path: 'crops', loadComponent: () => import('./features/crops/crops.page').then((m) => m.CropsPage), data: { title: 'المحاصيل' } },
      { path: 'crops/:slug', loadComponent: () => import('./features/crops/crop-details.page').then((m) => m.CropDetailsPage) },
      { path: 'crop-assistant', loadComponent: () => import('./features/problem-finder/crop-assistant.page').then((m) => m.CropAssistantPage), data: { title: 'المساعد الذكي' } },
      { path: 'compare', loadComponent: () => import('./features/comparison/comparison.page').then((m) => m.ComparisonPage), data: { title: 'المقارنة' } },
      { path: 'wishlist', loadComponent: () => import('./features/wishlist/wishlist.page').then((m) => m.WishlistPage), data: { title: 'المفضلة' } },
      { path: 'cart', loadComponent: () => import('./features/cart/cart.page').then((m) => m.CartPage), data: { title: 'السلة' } },
      { path: 'academy', loadComponent: () => import('./features/academy/academy.page').then((m) => m.AcademyPage), data: { title: 'الأكاديمية' } },
      { path: 'academy/category/:slug', loadComponent: () => import('./features/academy/academy.page').then((m) => m.AcademyPage) },
      { path: 'academy/articles/:slug', loadComponent: () => import('./features/academy/article.page').then((m) => m.ArticlePage) },
      { path: 'about', loadComponent: () => import('./features/about/about.page').then((m) => m.AboutPage), data: { title: 'عن نبته' } },
      { path: 'contact', loadComponent: () => import('./features/contact/contact.page').then((m) => m.ContactPage), data: { title: 'تواصل معنا' } },
      { path: 'faq', loadComponent: () => import('./features/about/faq.page').then((m) => m.FaqPage), data: { title: 'الأسئلة الشائعة' } },
      { path: 'policies/privacy', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'privacy' } },
      { path: 'policies/terms', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'terms' } },
      { path: 'policies/shipping', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'shipping' } },
      { path: 'policies/returns', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'returns' } },
      { path: 'policies/payment', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'payment' } },
      { path: 'policies/cookies', loadComponent: () => import('./features/policies/policy.page').then((m) => m.PolicyPage), data: { policy: 'cookies' } },
      { path: 'unauthorized', loadComponent: () => import('./features/system/system.page').then((m) => m.UnauthorizedPage) },
      { path: 'error', loadComponent: () => import('./features/system/system.page').then((m) => m.ErrorPage) },
      {
        path: 'account',
        canActivate: [authGuard],
        children: [
          { path: '', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountDashboardPage), data: { title: 'حسابي' } },
          { path: 'profile', pathMatch: 'full', redirectTo: '' },
          { path: 'orders', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountOrdersPage), data: { title: 'طلباتي' } },
          { path: 'orders/:id', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountOrderDetailsPage) },
          { path: 'addresses', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountAddressesPage), data: { title: 'العناوين' } },
          { path: 'wishlist', pathMatch: 'full', redirectTo: '/wishlist' },
          { path: 'recently-viewed', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountRecentPage), data: { title: 'شوهد مؤخرًا' } },
          { path: 'notifications', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountNotificationsPage), data: { title: 'الإشعارات' } },
          { path: 'security', loadComponent: () => import('./features/account/account.pages').then((m) => m.AccountSecurityPage), data: { title: 'الأمان' } },
        ],
      },
    ],
  },
  {
    path: 'auth',
    canActivate: [guestGuard],
    loadComponent: () => import('./core/layout/auth-layout.component').then((m) => m.AuthLayoutComponent),
    children: [
      {
        path: 'login',
        loadComponent: () => import('./features/auth/login.page').then((m) => m.LoginPage),
        data: { centeredAuth: true },
      },
      {
        path: 'register',
        loadComponent: () => import('./features/auth/register.page').then((m) => m.RegisterPage),
        data: { centeredAuth: true },
      },
      { path: 'forgot-password', loadComponent: () => import('./features/auth/forgot-password.page').then((m) => m.ForgotPasswordPage) },
      { path: 'reset-password', loadComponent: () => import('./features/auth/forgot-password.page').then((m) => m.ResetPasswordPage) },
      { path: 'verify-phone', loadComponent: () => import('./features/auth/forgot-password.page').then((m) => m.VerifyPhonePage) },
      { path: '', pathMatch: 'full', redirectTo: 'login' },
    ],
  },
  {
    path: 'checkout',
    loadComponent: () => import('./core/layout/auth-layout.component').then((m) => m.AuthLayoutComponent),
    children: [
      { path: '', loadComponent: () => import('./features/checkout/checkout.page').then((m) => m.CheckoutPage) },
      { path: 'success/:orderNumber', loadComponent: () => import('./features/checkout/checkout-result.page').then((m) => m.CheckoutSuccessPage) },
      { path: 'failure', loadComponent: () => import('./features/checkout/checkout-result.page').then((m) => m.CheckoutFailurePage) },
    ],
  },
  {
    path: 'admin',
    canActivate: [adminGuard],
    loadComponent: () => import('./core/layout/admin-layout.component').then((m) => m.AdminLayoutComponent),
    children: [
      { path: '', pathMatch: 'full', redirectTo: 'dashboard' },
      { path: 'dashboard', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminDashboardPage) },
      { path: 'products', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminProductsPage) },
      { path: 'products/new', loadComponent: () => import('./features/admin/admin-product-form.page').then((m) => m.AdminProductFormPage), canDeactivate: [unsavedChangesGuard] },
      { path: 'products/:id/edit', loadComponent: () => import('./features/admin/admin-product-form.page').then((m) => m.AdminProductFormPage), canDeactivate: [unsavedChangesGuard] },
      { path: 'categories', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminCategoriesPage) },
      { path: 'companies', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminCompaniesPage) },
      { path: 'brands', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminBrandsPage) },
      { path: 'crops', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminCropsPage) },
      { path: 'problems', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminProblemsPage) },
      { path: 'orders', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminOrdersPage) },
      { path: 'orders/:id', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminOrderDetailsPage) },
      { path: 'customers', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminCustomersPage) },
      { path: 'articles', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminArticlesPage) },
      { path: 'articles/new', loadComponent: () => import('./features/admin/admin-article-form.page').then((m) => m.AdminArticleFormPage), canDeactivate: [unsavedChangesGuard] },
      { path: 'articles/:id/edit', loadComponent: () => import('./features/admin/admin-article-form.page').then((m) => m.AdminArticleFormPage), canDeactivate: [unsavedChangesGuard] },
      { path: 'reviews', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminReviewsPage) },
      { path: 'coupons', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminCouponsPage) },
      { path: 'inventory', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminInventoryPage) },
      { path: 'messages', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminMessagesPage) },
      { path: 'settings', loadComponent: () => import('./features/admin/admin.pages').then((m) => m.AdminSettingsPage) },
    ],
  },
  {
    path: '**',
    loadComponent: () => import('./core/layout/public-layout.component').then((m) => m.PublicLayoutComponent),
    children: [{ path: '', loadComponent: () => import('./features/system/system.page').then((m) => m.NotFoundPage) }],
  },
];
