import { computed, inject, Injectable, signal } from '@angular/core';
import { catchError, delay, finalize, Observable, of, take, tap } from 'rxjs';
import { environment } from '../../../../environments/environment';
import { ReturnFilters, ReturnRequest, ReturnsPage, ReturnsSummary } from '../models/returns.models';
import { ReturnsApiService } from './returns-api.service';
import { DEMO_RETURNS } from './returns.demo';

export const DEFAULT_RETURN_FILTERS: ReturnFilters = { search: '', status: '', refundMethod: '', period: 'all', page: 1, perPage: 5 };
@Injectable() export class ReturnsStore {
  private readonly api = inject(ReturnsApiService); private readonly pageState = signal<ReturnsPage | null>(null); private readonly filtersState = signal(DEFAULT_RETURN_FILTERS); private readonly loadingState = signal(false); private readonly errorState = signal<string | null>(null); private readonly downloadingState = signal(false);
  readonly page = this.pageState.asReadonly(); readonly filters = this.filtersState.asReadonly(); readonly loading = this.loadingState.asReadonly(); readonly error = this.errorState.asReadonly(); readonly downloading = this.downloadingState.asReadonly(); readonly items = computed(() => this.pageState()?.items ?? []); readonly summary = computed<ReturnsSummary>(() => this.pageState()?.summary ?? { total: 0, awaitingReceipt: 0, inspecting: 0, refundedAmount: 0, refundedCount: 0 }); readonly totalPages = computed(() => Math.max(1, Math.ceil((this.pageState()?.total ?? 0) / this.filtersState().perPage))); readonly hasFilters = computed(() => { const f = this.filtersState(); return !!(f.search || f.status || f.refundMethod || f.period !== 'all'); });
  setFilters(patch: Partial<ReturnFilters>): void { this.filtersState.update((value) => ({ ...value, ...patch })); }
  reset(): void { this.filtersState.set(DEFAULT_RETURN_FILTERS); }
  load(): Observable<ReturnsPage> { this.loadingState.set(true); this.errorState.set(null); const request = environment.demoAdmin ? this.demo(this.filtersState()) : this.api.list(this.filtersState()); return request.pipe(tap((page) => this.pageState.set(page)), catchError(() => { this.errorState.set('تعذر تحميل طلبات المرتجعات.'); return of(this.pageState() ?? { items: [], summary: this.summary(), total: 0, page: 1, perPage: 5 }); }), finalize(() => this.loadingState.set(false))); }
  download(): void { if (this.downloadingState()) return; this.downloadingState.set(true); const source = environment.demoAdmin ? of(this.csv()).pipe(delay(180)) : this.api.report(this.filtersState()); source.pipe(take(1), tap((blob) => this.save(blob)), catchError(() => { this.errorState.set('تعذر تنزيل تقرير المرتجعات.'); return of(null); }), finalize(() => this.downloadingState.set(false))).subscribe(); }
  private filtered(f: ReturnFilters): ReturnRequest[] { const search = f.search.trim().toLocaleLowerCase('ar'); const limit = f.period === 'today' ? 86400000 : f.period === 'week' ? 604800000 : f.period === 'month' ? 2592000000 : Infinity; return DEMO_RETURNS.filter((item) => (!search || [item.returnNumber, item.orderNumber, item.customerName].some((value) => value.toLocaleLowerCase('ar').includes(search))) && (!f.status || item.status === f.status) && (!f.refundMethod || item.refundMethod === f.refundMethod) && Date.now() - Date.parse(item.createdAt) <= limit); }
  private demo(f: ReturnFilters): Observable<ReturnsPage> { const rows = this.filtered(f); const refunded = rows.filter((i) => i.status === 'approved'); const summary = { total: rows.length, awaitingReceipt: rows.filter((i) => i.status === 'awaiting_receipt').length, inspecting: rows.filter((i) => i.status === 'inspecting').length, refundedAmount: refunded.reduce((sum, item) => sum + item.refundAmount, 0), refundedCount: refunded.length }; const start = (f.page - 1) * f.perPage; return of({ items: rows.slice(start, start + f.perPage), summary, total: rows.length, page: f.page, perPage: f.perPage }).pipe(delay(220)); }
  private csv(): Blob { const rows = this.filtered(this.filtersState()).map((i) => [i.returnNumber, i.orderNumber, i.customerName, i.productName, i.reason, i.refundAmount, i.status]); return new Blob(['\ufeff', [['رقم المرتجع', 'رقم الطلب', 'العميل', 'المنتج', 'سبب الإرجاع', 'مبلغ الاسترداد', 'الحالة'], ...rows].map((row) => row.map((cell) => `"${cell}"`).join(',')).join('\r\n')], { type: 'text/csv;charset=utf-8' }); }
  private save(blob: Blob): void { const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = `returns-${new Date().toISOString().slice(0, 10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
}
